import { useEffect, useState } from 'react';
import { IconBrandUnsplash } from '@tabler/icons-react';
import { useGroup, EASING_FUNCTIONS } from '@cirolee/tiny-motion';
import { cva } from 'class-variance-authority';
import Footer from '@/components/Footer';
import GalleryImage from '@/components/GalleryImage';
import Toaster from '@/components/Sonner';
import Segment from '@/components/Segment';
import Show from '@/components/Show';
import { getProfileImage } from '@/utils/utils';

const container = cva(
  'mx-auto grid max-w-7xl grid-cols-2 justify-items-center gap-4 px-4 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6'
);

export default function Home() {
  const [tabValue, setTabValue] = useState('profile');
  const imageList = getProfileImage();
  const profileData = imageList.filter((item) => item.name?.startsWith('profile'));
  const transData = imageList.filter((item) => item.name?.startsWith('trans'));
  const emojiData = imageList.filter((item) => item.name?.startsWith('emoji'));
  const flatData = imageList.filter((item) => item.name?.startsWith('flat'));

  const controller = useGroup(
    {
      selectors: ['.gallery-image'],
      keyframes: { opacity: [0, 1], transform: ['translateY(14%)', 'translateY(0)'] },
      options: {
        duration: 500,
        fill: 'both',
        easing: EASING_FUNCTIONS.easeInSine,
        delay: (_, index) => {
          return index * 80;
        }
      }
    },
    [tabValue]
  );

  useEffect(() => {
    controller.play();
  }, [tabValue, controller]);
  return (
    <div className="h-screen overflow-auto">
      <div className="mt-10 mb-12 space-y-2 text-center">
        <h2 className="text-5xl font-medium text-white">Avatars</h2>
        <p className="text-base text-neutral-300">
          Free placeholder avatars, you can download them or copy the link to use in your project.
        </p>
      </div>
      <div className="flex justify-center">
        <Segment
          defaultValue="profile"
          className="mb-4"
          options={[
            { label: 'Profile', value: 'profile' },
            { label: 'Bg removed', value: 'bg-removed' },
            { label: 'Emoji', value: 'emoji' },
            { label: 'Flat', value: 'flat' }
          ]}
          onValueChange={setTabValue}
        />
      </div>
      <Show when={tabValue === 'profile'}>
        <div className={container()}>
          {profileData.map((item) => (
            <GalleryImage
              loading="lazy"
              className="opacity-0"
              tag={<IconBrandUnsplash size={12} />}
              src={item.src}
              key={item.key}
              alt={item.name}
              width={512}
              height={512}
            />
          ))}
        </div>
      </Show>
      <Show when={tabValue === 'bg-removed'}>
        <div className={container()}>
          {transData.map((item) => (
            <GalleryImage
              className="opacity-0"
              loading="lazy"
              tag="AI"
              src={item.src}
              key={item.key}
              alt={item.name}
              width={512}
              height={512}
            />
          ))}
        </div>
      </Show>
      <Show when={tabValue === 'emoji'}>
        <div className={container()}>
          {emojiData.map((item) => (
            <GalleryImage
              className="opacity-0"
              loading="lazy"
              tag="AI"
              src={item.src}
              key={item.key}
              alt={item.name}
              width={512}
              height={512}
            />
          ))}
        </div>
      </Show>
      <Show when={tabValue === 'flat'}>
        <div className={container()}>
          {flatData.map((item) => (
            <GalleryImage
              className="opacity-0 [&_img]:scale-[0.85]"
              loading="lazy"
              src={item.src}
              key={item.key}
              alt={item.name}
              width={512}
              height={512}
            />
          ))}
        </div>
      </Show>
      <p className="pt-20 pb-16 text-center text-sm text-neutral-400">
        The images are taken from the free items in{' '}
        <a
          href="https://unsplash.com"
          target="_blank"
          className="text-blue-500 underline underline-offset-2"
          rel="noopener noreferrer">
          Unsplash
        </a>{' '}
        or generated by AI.
      </p>
      <Footer />
      <Toaster />
    </div>
  );
}
